export const QUOTES_ARRAY = [
    "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does.",
    "Livet kan kun forstås baglæns; men det må leves forlæns. <br>Life can only be understood backwards; but it must be lived forwards.",
    "La liberté, c'est ce que vous faites de ce qui a été fait de vous.<br>Freedom is what you do with what's been done to you.",
    "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.",
    "You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.",
    "賢者の足跡をたどるな。賢者が目指したものを目指せ。<br>Do not seek to follow in the footsteps of the wise; seek what they sought.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "L'homme n'est rien d'autre que ce qu'il se fait. <br>Man is nothing else but what he makes of himself.",
    "Every man must decide whether he will walk in the light of creative altruism or in the darkness of destructive selfishness.",
    "Die Welt ist meine Vorstellung. <br>The world is my representation.",
    "Allein zu leben ist das Schicksal aller großen Seelen. <br>To live alone is the fate of all great souls.",
    "Ohne Musik wäre das Leben ein Irrtum. <br>Without music, life would be a mistake.",
    "Wer ein Warum zum Leben hat, erträgt fast jedes Wie. <br>He who has a why to live can bear almost any how.",
    "Zu leben ist Leiden, zu überleben ist, in dem Leiden einen Sinn zu finden. <br>To live is to suffer, to survive is to find meaning in the suffering.",
    "The mystery of human existence lies not in just staying alive, but in finding something to live for.",
    "Лучше идти своим путем ошибаясь, чем идти по чужому пути, но правильно. <br>It is better to go wrong in your own way than to go right in someone else's.",
    "Человек считает только свои беды; он не считает своего счастья. <br>Man only counts his troubles; he does not calculate his happiness.",
    "Der Mensch kann zwar tun, was er will, aber er kann nicht wollen, was er will. <br>Man can do what he wills, but he cannot will what he wills.",
    "La liberté de l'homme ne consiste pas à faire ce qu'il veut, mais à ne pas faire ce qu'il ne veut pas. <br>Man's freedom does not consist in doing what he wants, but in not doing what he does not want.",
    "L'homme est la seule créature qui refuse d'être ce qu'elle est. <br>Man is the only creature who refuses to be what he is.",
    "Toutes les actions humaines sont équivalentes et toutes sont sur le principe vouées à l'échec. <br>All human actions are equivalent and all are on principle doomed to failure.",
    "Das Glück ist nicht ein Ideal der Vernunft, sondern der Phantasie. <br>Happiness is not an ideal of reason but of imagination.",
    "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    "武士は常に死に備えなければならない——自分の死か、他人の死か。<br>A samurai should always be prepared for death - whether his own or someone else's.",
    "真の美しさとは、攻撃し、圧倒し、奪い、そして最終的に破壊するものである。<br>True beauty is something that attacks, overpowers, robs, and finally destroys.",
    "Find what you love and let it kill you.",
    "What matters most is how well you walk through the fire.",
    "痛みは避けられないが、苦しみは選択である。<br>Pain is inevitable. Suffering is optional.",
    "Die größten und wichtigsten Probleme des Lebens sind grundsätzlich unlösbar. Sie können niemals gelöst, sondern nur überwunden werden.",
    "The loneliest moment in someone’s life is when they are watching their whole world fall apart, and all they can do is stare blankly.",
    "It is not society that is to guide and save the creative hero, but precisely the reverse.",
    "If you're going through hell, keep going.",
    "Zu leben ist Leiden, zu überleben ist, in dem Leiden einen Sinn zu finden. <br>To live is to suffer, to survive is to find meaning in the suffering.",
    "Angst ist der Schwindel der Freiheit. <br>Anxiety is the dizziness of freedom.",
    "ألم أن تكون إنسانًا هو الصراع الأبدي بين الروح وما يحيط بها.<br>The pain of being human is the eternal struggle between one's soul and one's surroundings.",
    "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
    "狂った世界では、狂った人々だけが正気である。<br>In a mad world, only the mad are sane.",
    "The blood of the heroes is closer to God than the ink of the philosophers and the prayers of the faithful",

    // Added below
    "Existence precedes essence.",
    "Hell is other people.",
    "He who climbs upon the highest mountains laughs at all tragedies, real or imaginary.",
    "The wound is the place where the light enters you.",
    "No tree can grow to heaven unless its roots reach down to hell.",
    "One must imagine Sisyphus happy.",
    "What we fear doing most is usually what we most need to do.",
    "If you gaze long into an abyss, the abyss also gazes into you.",
    "The greatest burden a man can bear is the unfulfilled potential of his own soul.",
    "To have become what one is, one must not have the faintest notion what one is.",
    "When we are no longer able to change a situation, we are challenged to change ourselves.",
    "The privilege of a lifetime is to become who you truly are.",
    "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.",
    "Loneliness does not come from having no one around, but from being unable to communicate the things that matter.",
    "He who fears he will suffer, already suffers from his fear.",
    "All the world's a stage, and all the men and women merely players.",
    "You become responsible, forever, for what you have tamed.",
    "Do what you can, with what you have, where you are."
];
